version: 'latest'

services:
  db:
    image: postgres:latest
    platform: linux/x86_64
    container_name: library_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library_network
volumes:
  db_data:
  
networks:
    library_network:
      